trigger:
- main  # Change this based on your branch

pool:
  name: 'Default'  # Using a Microsoft-hosted agent

steps:
- checkout: self
  persistCredentials: true

- task: PowerShell@2
  displayName: 'Download Checkmarx CLI'
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -Uri "https://download.checkmarx.com/cli/latest/cx.exe" -OutFile "$(Build.ArtifactStagingDirectory)\cx.exe"

- task: CmdLine@2
  displayName: 'Run IaC Scan'
  inputs:
    script: |
      $(Build.ArtifactStagingDirectory)\cx.exe scan create --project-name "AzureDevOps_IaC_Scan" --repo "https://github.com/Abdul1110/terraform" --branch "main" --scan-types "iac" --base-uri "https://eu.ast.checkmarx.net" --client-id "xyz" --client-secret "r5sPMcb4C9YWi5m0tHwGFshGHiqbtLpW"

- task: PublishBuildArtifacts@1
  displayName: 'Publish Scan Report'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'ScanResults'
