name: Checkmarx Security Scan

on:
  push:
    branches:
      - main
      - test
      - dev
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checkmarx-ast:
    permissions:
      contents: read 
      security-events: write 
      actions: read

    runs-on: ubuntu

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run Checkmarx AST Scan
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          base_uri: https://anz.ast.checkmarx.net
          cx_tenant: michael
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}

  checkmarx-dast:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Checkmarx DAST Scan
        uses: Checkmarx/dast-github-action@v2.3.0
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        with:
          # The type of scan to perform (web, api)
          command: web
          # The path to the ZAP configuration file
          config: ./gin_juice.yaml
          # The base URL for the Checkmarx One Servers
          base_url: https://eu.iam.checkmarx.net/
          # The environment ID previously created in the Frontend
          environment_id: bd462e37-c712-440a-9e0c-7984b09d5252
          output: ${{ github.workspace }}/output_fold #./output

      - name: Upload DAST Logs
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: ${{ github.workspace }}/output_fold
	
      - name: Reclaim Output Directory
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_fold
